apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
namespace: ocp-prod-1 
resources: 
  - ../../base 
configMapGenerator: 
  - name: sentiment-api-config 
    literals: 
      - APP_ENV=prod 
      - MODEL_NAME=distilbert-base-uncased-finetuned-sst-2-english 
      - LOG_LEVEL=WARNING 
images: 
  - name: docker.io/vardhanv18/sentiment-api 
    newTag: prod-latest 
